Amplitude.init({
"songs": [

{
"name": "Sorry",
"artist": "Justin Bieber",
"url": "https://topghanamusic.com/wp-content/uploads/2025/07/Justin-Bieber-Sorry-(TopGhanaMusic.Com).mp3",
"cover_art_url": "https://i.postimg.cc/HxtL5yXw/1.png" },

{
"name": "WALK",
"artist": "Wallker",
"url": "drill/WALK.mp3",
"cover_art_url": "album/cover/drilland.jpg" },

{
"name": "LOVE V",
"artist": "Wallker",
"url": "drill/LOVE V.mp3",
"cover_art_url": "album/cover/drilland.jpg" },

{
"name": "LOST",
"artist": "Wallker",
"url": "drill/LOST.mp3",
"cover_art_url": "album/cover/drilland.jpg" },

{
"name": "CRY",
"artist": "Wallker",
"url": "drill/CRY.mp3",
"cover_art_url": "album/cover/drilland.jpg" }] });



 