Amplitude.init({
"songs": [

{
"name": "Sorry",
"artist": "Justin Bieber",
"url": "https://topghanamusic.com/wp-content/uploads/2025/07/Justin-Bieber-Sorry-(TopGhanaMusic.Com).mp3",
"cover_art_url": "https://i.postimg.cc/zf43vDq5/2025-09-22-20-44-16-artworks-000261882173-b14ar2-t240x240.jpg" },

{
"name": "Ghost",
"artist": "Justin Bieber",
"url": "https://www.thinkmusic.com.ng/thinknews/uploads/2025/06/Justin_Bieber_-_Ghost_thinknews.com.ng.mp3",
"cover_art_url": "https://i.postimg.cc/gjgSnxLJ/Stream-Justin-Bieber-Ghost-by-Kixibee-Listen-online-for-free.jpg" }] });



 